apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      author: uche
  template:
    metadata:
      labels:
        author: uche
    spec:
      containers:
      - name: api-app
        image: ucheenyi/api-app:v1
---
apiVersion: v1
kind: Service
metadata:
  name: api-app-service
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 6000
    targetPort: 6000
    nodePort: 30006
